# Generated by Django 3.0.8 on 2020-07-22 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='dis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images/photos'),
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='mypics', max_length=200),
            preserve_default=False,
        ),
    ]
