# Generated by Django 3.0.8 on 2020-07-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0002_auto_20200722_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='dis',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
    ]
