# Generated by Django 3.0.8 on 2020-07-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0003_auto_20200722_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='pic',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/photos/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
